### ISSUE TITLE
bazel build error

### ISSUE THREAD

**Issue by yangshao** [amutu/tensorflow-offline#3]
Hi, I successfully execute the first step, but when I execute the second step, i get the following error:
ERROR: /home/ec2-user/tensorflow-1.2.1/third_party/py/python_configure.bzl:285:20: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/py/python_configure.bzl' has errors.

How to fix this?

**Comment by amutu** [comment]
Please use tensorflow-1.2.0 instead of 1.2.1，the offline package and patches should be updated for  1.2.1.

**Comment by yangshao** [comment]
I solve this by updating the bazel version. and the build works. but i found the built tensorflow cannot work with gpu. Is there any way to compile a gpu version tensorflow offline?

**Comment by amutu** [comment]
It does not support GPU. I make this mainly for FreeBSD and FreeBSD do not have CUDA now.
