### ISSUE TITLE
@local_config_cuda//cuda not found

### ISSUE THREAD

**Issue by xiaoweiChen** [amutu/tensorflow-offline#4]
I am a beginner for bazel. And my server can not connect Internet, when I compile tensorflow.

Thanks your job, I get the dependences offline(I use 1.2.1 version), and successful get CPU version.

Now, I want to compile GPU version tensorflow.

I add something relation with CUDA in "./configure" step.

And run 

> bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

However, I get something wrong here:
```
ERROR: error loading package 'tensorflow/tools/pip_package': Rncountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda':Traceback(most recent call last): 
File “XX/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl”, line 958
_create_cuda_repository(repository_ctx)
File “XX/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl”, line 915, in _create_cuda_repository
_host_compiler_includes(repository_ctx, cc)
File “XX/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl”, line 144, in _host_compiler_includes
get_cxx_inc_directories(repository_ctx,cc)
File “XX/tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl”, line 119, in get_cxx_inc_directories
set(includes_cpp)
depsets cannot contain mutable items
```

While, I found "local_config_cuda" and "@local_config_cuda.marker" in thensorflow_third_party-1.2.1 directory.

**My Question**
How to make brazel find "local_config_cuda" and "@local_config_cuda.marker" ?

Maybe, Brazel would going well, when find these two files.

**Comment by amutu** [comment]
It does not work with CUDA now as the third party package generated without CUDA configuration.

**Comment by xiaoweiChen** [comment]
Thanks your reply amutu, and your great work for under GFW people.
Finally, I connect the network on my server by proxy and get gpu version Tensorflow.
